import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Position, Site, Department } from '@/types/core';
import { Head, Link, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';

export default function Form({ item, departments = [] }: { item: Position | null; departments: Pick<Department, 'id' | 'name'>[] }) {
 const isEdit=Boolean(item); const { data,setData,post,put,processing,errors }=useForm({ department_id: item?.department_id?.toString() ?? '',code: item?.code?.toString() ?? '',name: item?.name?.toString() ?? '', is_active: item?.is_active ?? true });
 function submit(event: FormEvent) { event.preventDefault(); isEdit ? put(route('core.positions.update', item!.id)) : post(route('core.positions.store')); }
 return <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-gray-800 dark:text-gray-200">{isEdit ? 'Edit Position' : 'New Position'}</h2>}><Head title={isEdit ? 'Edit Position' : 'New Position'} />
  <div className="py-12"><div className="mx-auto max-w-3xl sm:px-6 lg:px-8"><form onSubmit={submit} className="space-y-6 bg-white p-6 shadow-sm sm:rounded-lg dark:bg-gray-800"><div className="grid gap-4 sm:grid-cols-2"><Field label="Department" error={errors.department_id}><select className="w-full rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={data.department_id} onChange={e=>setData('department_id', e.target.value)}><option value="">No department</option>{departments.map((option)=><option key={option.id} value={option.id}>{option.name}</option>)}</select></Field><Field label="Code" error={errors.code}><input className="w-full rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={data.code} onChange={e=>setData('code', e.target.value)} /></Field><Field label="Name" error={errors.name}><input className="w-full rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={data.name} onChange={e=>setData('name', e.target.value)} /></Field><label className="flex items-center gap-2 pt-8 text-sm text-gray-700 dark:text-gray-200"><input type="checkbox" checked={data.is_active} onChange={e=>setData('is_active', e.target.checked)} /> Active</label></div><div className="flex justify-end gap-3"><Link href={route('core.positions.index')} className="rounded-md px-4 py-2 text-gray-700 dark:text-gray-200">Cancel</Link><button disabled={processing} className="rounded-md bg-indigo-600 px-4 py-2 text-white disabled:opacity-50">Save</button></div></form></div></div></AuthenticatedLayout>;
}
function Field({ label,error,children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-gray-700 dark:text-gray-200"><span>{label}</span><div className="mt-1">{children}</div>{error && <p className="mt-1 text-sm text-red-600">{error}</p>}</label>; }
