<?php

namespace App\Core\Permissions;

final class CorePermissions
{
    public static function all(): array
    {
        return [
            'core.sites.view',
            'core.sites.create',
            'core.sites.update',
            'core.sites.deactivate',
            'core.areas.view',
            'core.areas.create',
            'core.areas.update',
            'core.areas.deactivate',
            'core.departments.view',
            'core.departments.create',
            'core.departments.update',
            'core.departments.deactivate',
            'core.positions.view',
            'core.positions.create',
            'core.positions.update',
            'core.positions.deactivate',
            'core.companies.view',
            'core.companies.create',
            'core.companies.update',
            'core.companies.deactivate',
            'core.employees.view',
            'core.employees.create',
            'core.employees.update',
            'core.employees.deactivate',
            'core.users.view',
            'core.users.create',
            'core.users.update',
            'core.users.deactivate',
            'core.severities.view',
            'core.severities.create',
            'core.severities.update',
            'core.severities.deactivate',
            'core.priorities.view',
            'core.priorities.create',
            'core.priorities.update',
            'core.priorities.deactivate',
            'core.statuses.view',
            'core.statuses.create',
            'core.statuses.update',
            'core.statuses.deactivate',
            'core.categories.view',
            'core.categories.create',
            'core.categories.update',
            'core.categories.deactivate',
            'core.risk-matrix.view',
            'core.risk-matrix.create',
            'core.risk-matrix.update',
            'core.risk-matrix.deactivate',
            'core.files.view',
            'core.files.upload',
            'core.files.download',
            'core.files.delete',
            'core.numbering.view',
            'core.numbering.create',
            'core.numbering.update',
            'core.numbering.generate',
            'core.workflow.view',
            'core.workflow.manage',
            'core.workflow.transition',
            'core.audit.view',
            'core.comments.view',
            'core.comments.create',
            'core.comments.delete',
            'core.activity.view',
            'core.notifications.view',
            'core.notifications.manage',
            'core.export.csv',
            'core.roles.manage',
            'core.scope.own',
            'core.scope.department',
            'core.scope.site',
            'core.scope.company',
            'core.scope.all',
        ];
    }

    public static function roleMap(): array
    {
        $viewOnly = [
                'core.sites.view',
                'core.areas.view',
                'core.departments.view',
                'core.positions.view',
                'core.companies.view',
                'core.employees.view',
                'core.users.view',
                'core.severities.view',
                'core.priorities.view',
                'core.statuses.view',
                'core.categories.view',
                'core.risk-matrix.view',
                'core.files.view',
                'core.files.download',
                'core.numbering.view',
                'core.workflow.view',
                'core.audit.view',
                'core.comments.view',
                'core.activity.view',
                'core.notifications.view',
        ];

        return [
            'Super Admin' => self::all(),
            'Admin' => self::all(),
            'QHSSE Manager' => [...$viewOnly, 'core.scope.all'],
            'QHSSE Officer' => [...$viewOnly, 'core.scope.site'],
            'Supervisor' => ['core.companies.view', 'core.employees.view', 'core.departments.view', 'core.positions.view', 'core.scope.department'],
            'Department Head' => ['core.companies.view', 'core.employees.view', 'core.departments.view', 'core.positions.view', 'core.scope.department'],
            'Employee / Reporter' => ['core.scope.own'],
            'Contractor' => ['core.scope.company'],
            'Auditor' => [...$viewOnly, 'core.scope.all'],
            'Top Management' => [...$viewOnly, 'core.scope.all'],
        ];
    }
}
