import Pagination from '@/Components/Qhsse/Pagination';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Paginated } from '@/types/core';
import { Head, router, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';

interface Notification { id: number; type: string; title: string; message?: string | null; module_name?: string | null; reference_id?: number | null; action_url?: string | null; read_at?: string | null; created_at: string; actor?: { id: number; name: string; email: string } | null; }

export default function Index({ notifications, unreadCount }: { notifications: Paginated<Notification>; filters: { unread?: boolean }; unreadCount: number }) {
    const { data, setData, post, processing, errors } = useForm({ recipient_id: '', module_name: 'core.test', reference_id: '1' });
    function sendTest(event: FormEvent) { event.preventDefault(); post(route('core.notifications.test')); }
    function markRead(id: number) { router.patch(route('core.notifications.read', id)); }
    function markUnread(id: number) { router.patch(route('core.notifications.unread', id)); }
    function markAllRead() { router.patch(route('core.notifications.read-all')); }
    return <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-gray-800 dark:text-gray-200">Notifications</h2>}><Head title="Notifications"/><div className="py-12"><div className="mx-auto max-w-7xl space-y-6 sm:px-6 lg:px-8"><div className="rounded bg-white p-6 shadow-sm dark:bg-gray-800"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h3 className="font-semibold text-gray-900 dark:text-gray-100">Notification Center</h3><p className="text-sm text-gray-500">Unread: {unreadCount}</p></div><button onClick={markAllRead} className="rounded-md bg-gray-900 px-4 py-2 text-white dark:bg-gray-100 dark:text-gray-900">Mark all read</button></div></div><form onSubmit={sendTest} className="grid gap-3 rounded bg-white p-6 shadow-sm sm:grid-cols-4 dark:bg-gray-800"><input className="rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={data.recipient_id} onChange={(e)=>setData('recipient_id', e.target.value)} placeholder="recipient user id"/><input className="rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={data.module_name} onChange={(e)=>setData('module_name', e.target.value)} placeholder="module_name"/><input className="rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={data.reference_id} onChange={(e)=>setData('reference_id', e.target.value)} placeholder="reference_id"/><button disabled={processing} className="rounded-md bg-indigo-600 px-4 py-2 text-white disabled:opacity-50">Send Test</button>{errors.recipient_id && <p className="text-sm text-red-600 sm:col-span-4">{errors.recipient_id}</p>}</form><div className="overflow-hidden bg-white shadow-sm sm:rounded-lg dark:bg-gray-800"><div className="divide-y divide-gray-200 dark:divide-gray-700">{notifications.data.map((notification)=><div key={notification.id} className={`p-5 ${notification.read_at ? '' : 'bg-indigo-50 dark:bg-indigo-950/30'}`}><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="text-sm font-semibold text-gray-900 dark:text-gray-100">{notification.title}</div><div className="mt-1 text-sm text-gray-700 dark:text-gray-300">{notification.message}</div><div className="mt-1 text-xs text-gray-500">{notification.type} · {notification.module_name ?? '-'} #{notification.reference_id ?? '-'} · {notification.created_at}</div></div><div className="flex items-center gap-2">{notification.read_at ? <button onClick={()=>markUnread(notification.id)} className="text-sm text-indigo-600 dark:text-indigo-400">Mark unread</button> : <button onClick={()=>markRead(notification.id)} className="text-sm text-indigo-600 dark:text-indigo-400">Mark read</button>}</div></div></div>)}</div></div><Pagination links={notifications.links}/></div></div></AuthenticatedLayout>;
}
