import Pagination from '@/Components/Qhsse/Pagination';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Paginated } from '@/types/core';
import { Head, Link, router } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

interface AuditLog { id: number; event: string; auditable_type?: string | null; auditable_id?: number | null; module_name?: string | null; reference_id?: number | null; actor_name?: string | null; created_at: string; }

export default function Index({ logs, filters }: { logs: Paginated<AuditLog>; filters: { search?: string; event?: string; module_name?: string; auditable_type?: string } }) {
    const [search, setSearch] = useState(filters.search ?? '');
    const [event, setEvent] = useState(filters.event ?? '');
    const [moduleName, setModuleName] = useState(filters.module_name ?? '');
    function submit(e: FormEvent) { e.preventDefault(); router.get(route('core.audit-logs.index'), { search, event, module_name: moduleName }, { preserveState: true }); }
    return <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-gray-800 dark:text-gray-200">Audit Logs</h2>}><Head title="Audit Logs"/><div className="py-12"><div className="mx-auto max-w-7xl space-y-6 sm:px-6 lg:px-8"><form onSubmit={submit} className="flex flex-col gap-2 sm:flex-row"><input className="rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search"/><input className="rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={event} onChange={(e)=>setEvent(e.target.value)} placeholder="event"/><input className="rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={moduleName} onChange={(e)=>setModuleName(e.target.value)} placeholder="module_name"/><button className="rounded-md bg-gray-900 px-4 py-2 text-white dark:bg-gray-100 dark:text-gray-900">Search</button></form><div className="overflow-hidden bg-white shadow-sm sm:rounded-lg dark:bg-gray-800"><table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700"><thead className="bg-gray-50 dark:bg-gray-900"><tr><th className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">Event</th><th className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">Target</th><th className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">Actor</th><th className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">Time</th><th /></tr></thead><tbody className="divide-y divide-gray-200 dark:divide-gray-700">{logs.data.map((log)=><tr key={log.id}><td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{log.event}</td><td className="px-4 py-3 text-sm text-gray-700 dark:text-gray-300">{log.module_name ? `${log.module_name} #${log.reference_id}` : `${log.auditable_type?.split('\\').pop() ?? '-'} #${log.auditable_id ?? '-'}`}</td><td className="px-4 py-3 text-sm text-gray-700 dark:text-gray-300">{log.actor_name ?? '-'}</td><td className="px-4 py-3 text-sm text-gray-700 dark:text-gray-300">{log.created_at}</td><td className="px-4 py-3 text-right text-sm"><Link href={route('core.audit-logs.show', log.id)} className="text-indigo-600 dark:text-indigo-400">View</Link></td></tr>)}</tbody></table></div><Pagination links={logs.links}/></div></div></AuthenticatedLayout>;
}
