import Pagination from '@/Components/Qhsse/Pagination';
import StatusBadge from '@/Components/Qhsse/StatusBadge';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Paginated } from '@/types/core';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

interface WorkflowDefinition { id: number; module_name: string; code: string; name: string; initial_status: string; is_active: boolean; transitions_count: number; }
interface WorkflowInstance { id: number; module_name: string; reference_id: number; current_status: string; definition?: { id: number; name: string; module_name: string } | null; }

export default function Index({ definitions, instances, filters }: { definitions: Paginated<WorkflowDefinition>; instances: WorkflowInstance[]; filters: { search?: string } }) {
    const [search, setSearch] = useState(filters.search ?? '');
    const { data, setData, post, processing, errors } = useForm({ module_name: 'incident', reference_id: '1', action_key: '', reason: '' });

    function submitSearch(event: FormEvent) { event.preventDefault(); router.get(route('core.workflow.index'), { search }, { preserveState: true }); }
    function run(event: FormEvent) { event.preventDefault(); post(route('core.workflow.run')); }

    return <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-gray-800 dark:text-gray-200">Workflow Core</h2>}><Head title="Workflow Core"/><div className="py-12"><div className="mx-auto max-w-7xl space-y-6 sm:px-6 lg:px-8">
        <div className="grid gap-6 lg:grid-cols-3">
            <form onSubmit={run} className="space-y-4 bg-white p-6 shadow-sm sm:rounded-lg dark:bg-gray-800"><h3 className="font-semibold text-gray-900 dark:text-gray-100">Workflow Tester</h3><p className="text-xs text-gray-500">Leave action blank to start a workflow instance.</p><Field label="Module" error={errors.module_name}><input className="w-full rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={data.module_name} onChange={(e)=>setData('module_name',e.target.value)}/></Field><Field label="Reference ID" error={errors.reference_id}><input type="number" className="w-full rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={data.reference_id} onChange={(e)=>setData('reference_id',e.target.value)}/></Field><Field label="Action Key" error={errors.action_key}><input className="w-full rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={data.action_key} onChange={(e)=>setData('action_key',e.target.value)} placeholder="submit, review, reject"/></Field><Field label="Reason" error={errors.reason}><textarea className="w-full rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={data.reason} onChange={(e)=>setData('reason',e.target.value)}/></Field><button disabled={processing} className="rounded-md bg-gray-900 px-4 py-2 text-white disabled:opacity-50 dark:bg-gray-100 dark:text-gray-900">Run</button></form>
            <div className="bg-white p-6 shadow-sm sm:rounded-lg lg:col-span-2 dark:bg-gray-800"><div className="mb-4 flex justify-between gap-4"><form onSubmit={submitSearch} className="flex gap-2"><input className="rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search workflows"/><button className="rounded-md bg-gray-900 px-4 py-2 text-white dark:bg-gray-100 dark:text-gray-900">Search</button></form><Link href={route('core.workflow.history')} className="rounded-md bg-indigo-600 px-4 py-2 text-white">History</Link></div><table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700"><thead className="bg-gray-50 dark:bg-gray-900"><tr><th className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">Module</th><th className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">Initial</th><th className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">Transitions</th><th className="px-4 py-3 text-left text-xs font-medium uppercase text-gray-500">Status</th><th /></tr></thead><tbody className="divide-y divide-gray-200 dark:divide-gray-700">{definitions.data.map((definition)=><tr key={definition.id}><td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100"><div>{definition.name}</div><div className="text-xs text-gray-500">{definition.module_name}</div></td><td className="px-4 py-3 text-sm text-gray-700 dark:text-gray-300">{definition.initial_status}</td><td className="px-4 py-3 text-sm text-gray-700 dark:text-gray-300">{definition.transitions_count}</td><td className="px-4 py-3"><StatusBadge active={definition.is_active}/></td><td className="px-4 py-3 text-right text-sm"><Link href={route('core.workflow.show', definition.id)} className="text-indigo-600 dark:text-indigo-400">View</Link></td></tr>)}</tbody></table><Pagination links={definitions.links}/></div>
        </div>
        <div className="bg-white p-6 shadow-sm sm:rounded-lg dark:bg-gray-800"><h3 className="mb-4 font-semibold text-gray-900 dark:text-gray-100">Recent Instances</h3><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{instances.map((instance)=><div key={instance.id} className="rounded border border-gray-200 p-3 text-sm dark:border-gray-700"><div className="font-medium text-gray-900 dark:text-gray-100">{instance.module_name} #{instance.reference_id}</div><div className="text-xs text-gray-500">{instance.current_status}</div></div>)}</div></div>
    </div></div></AuthenticatedLayout>;
}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block text-sm font-medium text-gray-700 dark:text-gray-200"><span>{label}</span><div className="mt-1">{children}</div>{error&&<p className="mt-1 text-sm text-red-600">{error}</p>}</label>}
